name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  
  # Allows the workflow to be run manually from the Actions tab
  workflow_dispatch:

# The sequence of runs in this workflow
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Generate the snake animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Ad1tyaPatel  # Replace with your GitHub username
          # Generates the snake gif and svg on a branch called "output"
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Check the status of the build (useful for debugging)
      - run: git status

      # Push the changes to the repository
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Deploy the generated snake to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # The output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
